workspace:
  base: //home/javiroman/HACK/dev/javiroman-github/comodoo-org/ComodoWorkspace
  path: src/github.com/comodoo/hello-go

pipeline:
  build:
    image: golang:latest
    commands:
      - go get ./...
      - go build
